server:
  port: 8790
spring:
  application:
    name: hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname:ribbon
ribbon:
  eureka:
    enabled: true
